(function() {var implementors = {};
implementors["conrod"] = ["impl&lt;H&gt; <a class='trait' href='wayland_client/event_queue/trait.Init.html' title='wayland_client::event_queue::Init'>Init</a> for <a class='struct' href='wayland_window/decorated_surface/struct.DecoratedSurface.html' title='wayland_window::decorated_surface::DecoratedSurface'>DecoratedSurface</a>&lt;H&gt; <span class='where fmt-newline'>where H: 'static + <a class='trait' href='wayland_window/decorated_surface/trait.Handler.html' title='wayland_window::decorated_surface::Handler'>Handler</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a></span>",];
implementors["glutin"] = ["impl&lt;H&gt; <a class='trait' href='wayland_client/event_queue/trait.Init.html' title='wayland_client::event_queue::Init'>Init</a> for <a class='struct' href='wayland_window/decorated_surface/struct.DecoratedSurface.html' title='wayland_window::decorated_surface::DecoratedSurface'>DecoratedSurface</a>&lt;H&gt; <span class='where fmt-newline'>where H: 'static + <a class='trait' href='wayland_window/decorated_surface/trait.Handler.html' title='wayland_window::decorated_surface::Handler'>Handler</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a></span>",];
implementors["lazybox_graphics"] = ["impl&lt;H&gt; <a class='trait' href='wayland_client/event_queue/trait.Init.html' title='wayland_client::event_queue::Init'>Init</a> for <a class='struct' href='wayland_window/decorated_surface/struct.DecoratedSurface.html' title='wayland_window::decorated_surface::DecoratedSurface'>DecoratedSurface</a>&lt;H&gt; <span class='where fmt-newline'>where H: 'static + <a class='trait' href='wayland_window/decorated_surface/trait.Handler.html' title='wayland_window::decorated_surface::Handler'>Handler</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a></span>",];
implementors["wayland_window"] = ["impl&lt;H:&nbsp;<a class='trait' href='wayland_window/trait.Handler.html' title='wayland_window::Handler'>Handler</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + 'static&gt; <a class='trait' href='wayland_client/event_queue/trait.Init.html' title='wayland_client::event_queue::Init'>Init</a> for <a class='struct' href='wayland_window/struct.DecoratedSurface.html' title='wayland_window::DecoratedSurface'>DecoratedSurface</a>&lt;H&gt;",];
implementors["winit"] = ["impl&lt;H&gt; <a class='trait' href='wayland_client/event_queue/trait.Init.html' title='wayland_client::event_queue::Init'>Init</a> for <a class='struct' href='wayland_window/decorated_surface/struct.DecoratedSurface.html' title='wayland_window::decorated_surface::DecoratedSurface'>DecoratedSurface</a>&lt;H&gt; <span class='where fmt-newline'>where H: 'static + <a class='trait' href='wayland_window/decorated_surface/trait.Handler.html' title='wayland_window::decorated_surface::Handler'>Handler</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
